package itexto.neo4jviewer;

import java.awt.BorderLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kicolobo
 */
public class FMain extends javax.swing.JFrame {

    private JFileChooser fileChooser;

    private JFileChooser getFileChooser() {
        if (fileChooser == null) {
            fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        }
        return fileChooser;
    }

    /** Creates new form FMain */
    public FMain() {
        initComponents();
        setLocationRelativeTo(null);

        addWindowListener(new WindowListener() {

            public void windowOpened(WindowEvent e) {
                dbWrapper.closeDatabase();
            }

            public void windowClosing(WindowEvent e) {

            }

            public void windowClosed(WindowEvent e) {

            }

            public void windowIconified(WindowEvent e) {

            }

            public void windowDeiconified(WindowEvent e) {

            }

            public void windowActivated(WindowEvent e) {

            }

            public void windowDeactivated(WindowEvent e) {

            }
        });

    }

    private JFrame getMe() {
        return this;
    }

    private final DbWrapper dbWrapper = new DbWrapper();

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuOpenDatabase = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Neo4J Viewer");

        jMenu1.setText("File");

        mnuOpenDatabase.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnuOpenDatabase.setText("Open database");
        mnuOpenDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpenDatabaseActionPerformed(evt);
            }
        });
        jMenu1.add(mnuOpenDatabase);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-579)/2, (screenSize.height-449)/2, 579, 449);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuOpenDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpenDatabaseActionPerformed
        new Thread() {
            public void run() {
                try {
                    mnuOpenDatabase.setEnabled(false);
                    getFileChooser().showOpenDialog(getMe());
                    if (getFileChooser().getSelectedFile() != null) {
                        setTitle("Wait...");
                        dbWrapper.openDatabase(getFileChooser().getSelectedFile());
                        add(dbWrapper.getViewer(), BorderLayout.CENTER);
                        
                        if (dbWrapper.getDatabase() != null) {
                            setTitle("Neo4JViewer - " + dbWrapper.getDatabase().getStoreDir());
                        }
                    }
                } catch (Exception ex) {
                    setTitle("Neo4JViewer - by itexto");
                    JOptionPane.showMessageDialog(getMe(), ex);
                } finally {
                    mnuOpenDatabase.setEnabled(true);
                }
            }
        }.start();
    }//GEN-LAST:event_mnuOpenDatabaseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuOpenDatabase;
    // End of variables declaration//GEN-END:variables

}
